Audit Board create and delete pre-request scripts
BetterCloud-Customer-Engineering/BetterCloud-Custom-Integrations pull request #12
Opened 2022-02-25 23:42 UTC by cvkramer

Audit Board create and delete pre-request scripts

2022-03-01 16:42 UTC, joey-bc requested changes

2022-03-01 16:42 UTC, joey-bc commented on AuditBoard/getRoleIdAndFormatRequest.js
> +        console.log(err);
Remove this console log

2022-03-01 16:42 UTC, joey-bc commented on AuditBoard/getUserId.js
> +            matchingUser = users.find(user => user.email.toLowerCase() === email);
Maybe modify this to use filter and then check for edgecases like multiple users found and no users found

2022-03-01 16:42 UTC, joey-bc commented on AuditBoard/getRoleIdAndFormatRequest.js
> +        console.log(err);
Remove console log

2022-03-01 16:42 UTC, joey-bc commented on AuditBoard/getRoleIdAndFormatRequest.js
> +            matchingUser = users.find(user => user.email.toLowerCase() === email);
Change to filter and check for multiple and no user edgecases. Even though we should expect it to return 1, we should make sure we're erroring out just in case.

2022-03-07 22:41 UTC, cvkramer commented
I reworked this whole implementation to separate out all pre-request activities.

2022-03-07 23:03 UTC, closed without merging